# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  facebook_oauth_secret: 'Facebook oauth secret'
  google_oauth_secret: 'Google oauth secret'
  jwt_secret: supersecurestringyallwontevenknow
  jwt_algorithm: HS512
  secret_key_base: f927d1c0b4ec3c51be1cae93a56d8717a1debb91c07e7316f23ce412a9bf12a9d0980a695a26940872466fe5d2ec5881617078e1f7b4931c4f84cb05c0bf24a8

test:
  secret_key_base: d12c16d2dd24f3f0a43cd1f1e59d3100d87ad6caa93d219fd2a07e83d60f695535258ea20eded3499e57c7db56a6ebd3313044b88d987c35cf66e60b1e680d71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  facebook_oauth_secret: <%= ENV['FACEBOOK_SECRET'] %>
  google_oauth_secret: <%= ENV['GOOGLE_SECRET'] %>
  jwt_secret: <%= ENV['TOKEN_SECRET'] %>
  jwt_algorithm: HS512
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>